#!/usr/bin/lua

local uci = require('simple-uci').cursor()

uci:section('fastd', 'yolokey', 'yolokey_mesh_vpn',
	{
		key_uploaded = '0'  -- update shall trigger a key upload
	}
)
uci:section('fastd', 'fastd', 'mesh_vpn',
	{
		on_connect = '/lib/gluon/ffmr-yolokey-client.lua'
	}
)

uci:save('fastd')
uci:commit('fastd')
